server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Creates or updates the database schema automatically
    show-sql: true      # Logs SQL statements
    properties:
      hibernate:
        format_sql: true # Formats the SQL logs
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org.springframework.security: DEBUG
